---
http_interactions:
- request:
    method: delete
    uri: https://okta-test.okta.com/api/v1/apps/0oa6nmg6fdvwvoHwR0h7/groups/00g6nm9yt5VEl6xYd0h7
    body:
      encoding: UTF-8
      string: "{}"
    headers:
      User-Agent:
      - Oktakit v0.1.0
      Accept:
      - application/json
      Content-Type:
      - application/json
      Authorization:
      - SSWS  <<ACCESS_TOKEN>>
  response:
    status:
      code: 204
      message: 
    headers:
      date:
      - Thu, 14 Jul 2016 04:32:32 GMT
      server:
      - nginx
      x-okta-request-id:
      - V4cV4EkS67yJuNE68sz5HQAABLo
      x-rate-limit-limit:
      - '1200'
      x-rate-limit-remaining:
      - '1199'
      x-rate-limit-reset:
      - '1468470812'
      p3p:
      - CP="HONK"
      cache-control:
      - no-cache, no-store
      pragma:
      - no-cache
      expires:
      - '0'
      x-okta-backend:
      - op1-majorapp02a.aue1s.saasure.com
      x-frame-options:
      - SAMEORIGIN
      strict-transport-security:
      - max-age=315360000
      set-cookie:
      - sid=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/, JSESSIONID=D818F1B2AEADFDD0B2DA5695C1F9B41E;
        Path=/, JSESSIONID=D818F1B2AEADFDD0B2DA5695C1F9B41E; Path=/; Secure
      content-length:
      - '0'
      connection:
      - close
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 14 Jul 2016 04:32:32 GMT
- request:
    method: delete
    uri: https://okta-test.okta.com/api/v1/apps/0oa6nmg6fdvwvoHwR0h7/groups/00g6o0uh8xcL5WbyZ0h7
    body:
      encoding: UTF-8
      string: "{}"
    headers:
      User-Agent:
      - Oktakit v0.1.0
      Accept:
      - application/json
      Content-Type:
      - application/json
      Authorization:
      - SSWS  <<ACCESS_TOKEN>>
  response:
    status:
      code: 404
      message: 
    headers:
      date:
      - Thu, 14 Jul 2016 13:53:23 GMT
      server:
      - nginx
      content-type:
      - application/json
      vary:
      - Accept-Encoding
      x-okta-request-id:
      - V4eZU@XAfLU1ttNceQfNrAAAAyA
      x-rate-limit-limit:
      - '1200'
      x-rate-limit-remaining:
      - '1193'
      x-rate-limit-reset:
      - '1468504415'
      p3p:
      - CP="HONK"
      cache-control:
      - no-cache, no-store
      pragma:
      - no-cache
      expires:
      - '0'
      set-cookie:
      - sid=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/, JSESSIONID=4ED32F26247E9B4936600D4EC54015E0;
        Path=/
      connection:
      - close
      transfer-encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"errorCode":"E0000007","errorSummary":"Not found: Resource not found:
        00g6o0uh8xcL5WbyZ0h70oa6nmg6fdvwvoHwR0h7 (GroupAppAssignment)","errorLink":"E0000007","errorId":"oaeDOmY_ijmTWudBy3_gVbLQw","errorCauses":[]}'
    http_version: 
  recorded_at: Thu, 14 Jul 2016 13:53:23 GMT
recorded_with: VCR 3.0.3
