---
http_interactions:
- request:
    method: post
    uri: https://okta-test.okta.com/api/v1/apps/0oa6nmg6fdvwvoHwR0h7/users/00u6nm9ytbmwHeunx0h7
    body:
      encoding: UTF-8
      string: '{"credentials":{"userName":"user@example.com","password":{"value":"newPassword"}}}'
    headers:
      User-Agent:
      - Oktakit v0.1.0
      Accept:
      - application/json
      Content-Type:
      - application/json
      Authorization:
      - SSWS  <<ACCESS_TOKEN>>
  response:
    status:
      code: 200
      message: 
    headers:
      date:
      - Thu, 14 Jul 2016 04:36:43 GMT
      server:
      - nginx
      content-type:
      - application/json;charset=UTF-8
      vary:
      - Accept-Encoding
      x-okta-request-id:
      - V4cW2@XAfLU1ttNceQfFtAAAAyA
      x-rate-limit-limit:
      - '1200'
      x-rate-limit-remaining:
      - '1199'
      x-rate-limit-reset:
      - '1468471063'
      p3p:
      - CP="HONK"
      cache-control:
      - no-cache, no-store
      pragma:
      - no-cache
      expires:
      - '0'
      strict-transport-security:
      - max-age=315360000
      set-cookie:
      - sid=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/, JSESSIONID=3405E74BE2950161372DCDE3D8B3879A;
        Path=/
      connection:
      - close
      transfer-encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"id":"00u6nm9ytbmwHeunx0h7","externalId":null,"created":"2016-07-14T04:36:43.000Z","lastUpdated":"2016-07-14T04:36:43.000Z","scope":"USER","status":"ACTIVE","statusChanged":"2016-07-14T04:36:43.000Z","passwordChanged":null,"syncState":"DISABLED","lastSync":null,"credentials":{"userName":"user@example.com"},"profile":{},"_links":{"app":{"href":"https://okta-test.okta.com/api/v1/apps/0oa6nmg6fdvwvoHwR0h7"},"user":{"href":"https://okta-test.okta.com/api/v1/users/00u6nm9ytbmwHeunx0h7"}}}'
    http_version: 
  recorded_at: Thu, 14 Jul 2016 04:36:44 GMT
- request:
    method: post
    uri: https://okta-test.okta.com/api/v1/apps/0oa6nmg6fdvwvoHwR0h7/users/00u6o0w6tyuPVEeZr0h7
    body:
      encoding: UTF-8
      string: '{"credentials":{"userName":"user@example.com","password":{"value":"newPassword"}}}'
    headers:
      User-Agent:
      - Oktakit v0.1.0
      Accept:
      - application/json
      Content-Type:
      - application/json
      Authorization:
      - SSWS  <<ACCESS_TOKEN>>
  response:
    status:
      code: 500
      message: 
    headers:
      date:
      - Thu, 14 Jul 2016 13:53:22 GMT
      server:
      - nginx
      content-type:
      - application/json
      x-okta-request-id:
      - V4eZUttnJBqDdYPiZolb9AAAC28
      x-rate-limit-limit:
      - '1200'
      x-rate-limit-remaining:
      - '1198'
      x-rate-limit-reset:
      - '1468504415'
      p3p:
      - CP="HONK"
      cache-control:
      - no-cache, no-store
      pragma:
      - no-cache
      expires:
      - '0'
      set-cookie:
      - sid=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/, JSESSIONID=9D4EB7217DFA0388CB1CD50F73172834;
        Path=/
      connection:
      - close
      transfer-encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"errorCode":"E0000009","errorSummary":"Internal Server Error","errorLink":"E0000009","errorId":"oaeocmW62eoTm6L8K2MXcfrnQ","errorCauses":[]}'
    http_version: 
  recorded_at: Thu, 14 Jul 2016 13:53:22 GMT
recorded_with: VCR 3.0.3
